### ISSUE TITLE
powerbi cli commands errors

### ISSUE THREAD

**Issue by gdillen** [Microsoft/PowerBI-Cli#10]
Hello,

Trying on Mac/OSX powerbi cli, installed it globally.

The only command that works is "$ powerbi help"
When trying the others I get e.g.:
$ powerbi config
$ powerbi-config(1) does not exist, try --help

Or am I executing the commands in a wrong way?

Thanks.
Guy

**Comment by wbreza** [comment]
This is a known issue that we are tracking in #5.  Will close this as a duplicate.  In the meantime please try out the current workarounds listed in the bug.
