### ISSUE TITLE
All commands result in error "(1) does not exist", on mac osx

### ISSUE THREAD

**Issue by hanssens** [Microsoft/PowerBI-Cli#18]
After installing the powerbi-cli v1.0.0 on Mac OSX all commands fail with the following error message:

```
	$ powerbi get-workspaces -c "foo" -k <mykey>

	  powerbi-get-workspaces(1) does not exist, try --help
```

Same applies for other commands, the error _(1) does not exist_ always occurs. However, running the exact same command through the cli on Windows 10 works just fine.

Note: this may be related to issue #5, but it's a different error message.

I'm Running Node v6.1.0, NPM 3.8.6 on OSX 10.11.5

**Comment by wbreza** [comment]
Thanks for reporting @hanssens.  Yes, this is the same issue as #5.  We'll have a patch out for this soon.  Closing as a duplicate.

**Comment by stevenharman** [comment]
This does not seem to be the same issue as I've run `dos2unix` across the entire node modules directory and it's still happening.

**Comment by stevenharman** [comment]
A hack to work around this, for now: https://github.com/Microsoft/PowerBI-Cli/issues/5#issuecomment-251419579
