### ISSUE TITLE
Commands not working on macOS

### ISSUE THREAD

**Issue by kenmcode** [Microsoft/PowerBI-Cli#21]
I am still experience the same for v1.0.2 as #5 in that the powerbi -h works but any command returns:
 powerbi-config(1) does not exist, try --help   (from running powerbi config -h).

Tried on node v5.12.0 and v6.2.2 and ran the dos2unix on the powerbi-cli folder in node_modules as referenced in the stackoverflow solution but still receiving the same error. 

Same process is working fine on a windows machine.

**Comment by wbreza** [comment]
Closing this and reopend #5
