### ISSUE TITLE
Receiving Server Error 500 

### ISSUE THREAD

**Issue by mschulz531** [Microsoft/PowerBI-Cli#22]
Just started receiving Server Error 500 for this call...it was working earlier today.

U:\>powerbi update-connection -d 283117f9-####-####-####-cf493fcb924f -s 'DataSource=tcp:my##db.database.windows.net,1433;Initial Catalog=my##db'
[ powerbi ] Found dataset!
[ powerbi ] Id: 283117f9-####-####-####-cf493fcb924f
[ powerbi ] Name: DeviceTypes
[ powerbi ] Error updating connection string
[ powerbi ] {"error":{"code":"UnknownError","pbi.error":{"code":"UnknownError"}}}
[ powerbi ] Method:  POST
[ powerbi ] Url:  https://api.powerbi.com/v1.0/collections/ProActPortalWkspColl/workspaces/055cf866-####-####-####-72f65bae134e/datasets/283117f9-####-####-####-cf493fcb924f/Default.SetAllConnections
[ powerbi ] Status Code:  500
[ powerbi ] cache-control :  no-store, must-revalidate, no-cache
[ powerbi ] transfer-encoding :  chunked
[ powerbi ] content-type :  application/json; charset=utf-8
[ powerbi ] server :  Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
[ powerbi ] strict-transport-security :  max-age=31536000; includeSubDomains
[ powerbi ] x-frame-options :  deny
[ powerbi ] x-content-type-options :  nosniff
[ powerbi ] requestid :  2710c7b6-4984-4269-91ec-a5ea889b3b97
[ powerbi ] date :  Mon, 01 Aug 2016 15:57:34 GMT
[ powerbi ] connection :  close

**Comment by wbreza** [comment]
Hi @mschulz531.  I was able to look up your trace in our logs and found the following error.  Looks like something in your connection string was not valid.  Please double check your connection string and let me know if it works.

```
System.ArgumentException: Format of the initialization string does not conform to specification starting at index 60.
   at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, Int32 currentPosition, StringBuilder buffer, Boolean useOdbcRules, String& keyname, String& keyvalue)
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
```

**Comment by mschulz531** [comment]
Thanks Wallace,
I think the issue has been resolved...I believe this was caused by my
omission of the word "Data" from the Data Source= component of the
connection string.
Regards,
Mike

**Comment by wbreza** [comment]
Glad to hear - reach out if you run into any further issues.
