### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by julianmbs** [Microsoft/PowerBI-Cli#28]
I am getting this error when I use any command related to config option:

C:\>powerbi config
[ powerbi ] **EPERM: operation not permitted, open 'C:\.powerbirc'**

C:\>powerbi config -c NMBSReports -k 6X6......o/5g==
[ powerbi ] **EPERM: operation not permitted, open 'C:\.powerbirc'**

Other commands work fine. Do I need to create .powerbirc file? Or set up permissions? Where do I find that file?

**Comment by wbreza** [comment]
the CLI tool attempts to write a `.powerbirc` file to the current directory.  If you are running it a protected folder you may need to run as admin for the file to be generated successfully.

**Comment by julianmbs** [comment]
Thanks, running as admin solved the problem.
