### ISSUE TITLE
No datasources found within dataset

### ISSUE THREAD

**Issue by julianmbs** [Microsoft/PowerBI-Cli#29]
Hi,

Update-connection option says "No datasources found within dataset". What could be the reason?

C:\>powerbi import -n TestDirectQuery -f c:\_Data\PowerBI\TestDirectQuerytoDW2.pbix
[ powerbi ] Importing c:\_Data\PowerBI\TestDirectQuerytoDW2.pbix to workspace: af10b23d-9d8b-4996-94e0-c070a528e17e
[ powerbi ] File uploaded successfully
[ powerbi ] Import ID: f26b9b69-81d3-4e93-b80b-2dcbcd78d15f
[ powerbi ] Checking import state: Publishing
[ powerbi ] Checking import state: Publishing
[ powerbi ] Checking import state: Succeeded
[ powerbi ] Import succeeded

C:\>powerbi get-datasets
[ powerbi ] =========================================
[ powerbi ] Gettings datasets for Collection: af10b23d-9d8b-4996-94e0-c070a528e17e
[ powerbi ] =========================================
[ powerbi ] ID: 97b43f77-8d69-4742-b635-85558180a327 | Name: TestDirectQuery

C:\>powerbi update-connection -d 97b43f77-8d69-4742-b635-85558180a327 -u nmbs\#### -p ####
[ powerbi ] Found dataset!
[ powerbi ] Id: 97b43f77-8d69-4742-b635-85558180a327
[ powerbi ] Name: TestDirectQuery
[ powerbi ] Getting gateway datasources...
[ powerbi ] **No datasources found within dataset: 97b43f77-8d69-4742-b635-85558180a327**

Thanks,
Julia

**Comment by wbreza** [comment]
The error you are getting is typically seen when using the `Import` vs `Direct Query` data connection.

When viewing your file in Power BI Desktop do you see "Direct Query: Enabled" in the bottom right corner?

![image](https://cloud.githubusercontent.com/assets/6540159/17710180/038b2960-63a1-11e6-9d06-ad0a697348d4.png)

**Comment by julianmbs** [comment]
Yes, I do see "DirectQuery: Enabled" in the corner. That is why I am trying to use "update-connection" option, since I am getting this message for all of my DirectQuery reports (imported ones display fine).

![image](https://cloud.githubusercontent.com/assets/21040808/17710372/8d555826-63b2-11e6-9a0c-5fd781d62581.png)

**Comment by wbreza** [comment]
Thanks - Just needed to verify.  

Are you attempting to connect to an on-prem or cloud based datasource?  

Also - After clicking on `See Details` can you please provide the `Client Activity ID`.  I can use this information to lookup your issue in our logs.

**Comment by julianmbs** [comment]
It is SQL Server in Azure. Unfortunately, I am not able to click on "See Details", it does not respond.

Not sure if it's related, but when I am viewing another report that uses Import option, I can see the visuals, but I am not able to click on anything - can't change tabs, can't slice by clicking on a bar chart, etc.

**Comment by wbreza** [comment]
That is strange that you are unable to interact with the UI.  How are you embedding the reports?  Our sample app? or via your own application?  I'd recommend using [our sample](https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started-sample/) out of the box to get up and running to eliminate other potential issues.

**Comment by julianmbs** [comment]
Yes, I did use your sample application for provisioning, and I used [this sample](https://github.com/Azure-Samples/power-bi-embedded-iframe) for embedding reports in asp.net application.

**Comment by julianmbs** [comment]
Ok, I tried to run my reports using your [MVC sample application](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/). Reports that use Import option do respond normally. Reports that use DirectQuery option still show "Can't display the visual", but I was able to click on "See details". Activity ID - bbdc59b9-26bc-4c8a-984c-de05bd126edb.

**Comment by julianmbs** [comment]
Here is another Activity ID, for a report that uses SSAS - 49837823-9b4f-4e60-b54f-28fc7582da6a. Is SSAS supported?

**Comment by wbreza** [comment]
SSAS being Sql Server Analysis Services?  

We're investigating the traces and will get back to you with more inf.

For `49837823-9b4f-4e60-b54f-28fc7582da6a` I'm seeing that there is a mismatch between the worspace id and the workspace collection.  Verify that you are constructing the JWT Tokens correctly.

**Comment by julianmbs** [comment]
The only thing I changed in [your sample application](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/) was that I set the 4 settings in web.config, I didn't touch anything else.

![image](https://cloud.githubusercontent.com/assets/21040808/17714534/d91468fc-63c5-11e6-9a2c-59f0c7776a7b.png)

So I am not sure what you mean by constructing JWT Tokens correctly.

**Comment by wbreza** [comment]
Sure - I understand.  And you confirmed the `WorkspaceId` referenced is in the workspace collection `NMBSReports` ??

**Comment by julianmbs** [comment]
Yes, I just copied it from Azure portal

![image](https://cloud.githubusercontent.com/assets/21040808/17715774/520733fc-63cb-11e6-876e-7300120c6929.png)

**Comment by julianmbs** [comment]
All the other options do work fine, I am able to import a report into the workspace, and retrieve all the datasets from the workspace, so it tells me that WorkspaceId is set correctly. I am just not able to do "update-connection"...

**Comment by wbreza** [comment]
Hi @julianmbs - We have a theory.  Is this an older PBIX file that was used in the standard Power BI online service?  Try this - Ensure you have the latest version of Power BI Desktop.  Open the PBIX file in PBI Desktop, resave it and re-import it.

Hope this helps.

**Comment by julianmbs** [comment]
Hi,

I downloaded and installed the latest version of PBI Desktop, opened the file and re-saved it. Then I imported the file, and tried to update the connection, and got the same results:

C:\>powerbi import -f C:\_Data\PowerBI\TestDirectQueryDW.pbix -n TestDirectQueryNew
[ powerbi ] Importing C:\_Data\PowerBI\TestDirectQueryDW.pbix to workspace: af10b23d-9d8b-4996-94e0-c070a528e17e
[ powerbi ] File uploaded successfully
[ powerbi ] Import ID: d0b4a8ab-dc86-4a80-95bb-35b55896a14f
[ powerbi ] Checking import state: Publishing
[ powerbi ] Checking import state: Succeeded
[ powerbi ] Import succeeded

C:\>powerbi  get-datasets
[ powerbi ] =========================================
[ powerbi ] Gettings datasets for Collection: af10b23d-9d8b-4996-94e0-c070a528e17e
[ powerbi ] =========================================
[ powerbi ] ID: 97b43f77-8d69-4742-b635-85558180a327 | Name: TestDirectQuery
[ powerbi ] ID: 44f14ad1-67f1-4b40-b01e-a8207a8c8b19 | Name: TestDirectQueryNew

C:\>powerbi update-connection -d 44f14ad1-67f1-4b40-b01e-a8207a8c8b19 -u nmbs\jshah -p ####
[ powerbi ] Found dataset!
[ powerbi ] Id: 44f14ad1-67f1-4b40-b01e-a8207a8c8b19
[ powerbi ] Name: TestDirectQueryNew
[ powerbi ] Getting gateway datasources...
[ powerbi ] No datasources found within dataset: 44f14ad1-67f1-4b40-b01e-a8207a8c8b19

**Comment by wbreza** [comment]
Can you please run a fiddler trace during the import and provide the `RequestID` header from the failed request.

**Comment by julianmbs** [comment]
It doesn't fail during the import, it fails during update. But here are both:

RequestId for import: dbd91994-c32c-b6a6-5eb7-a9cb8a5f66b7
RequestId for update-connection: d98cf0dd-c930-ea33-c922-98a23d3c5e28

**Comment by wbreza** [comment]
There are a few other custom headers that I need to continue my review.  Can you just send me the full fiddler trace to wabreza @ microsoft.com?

**Comment by wbreza** [comment]
After following up with @julianmbs offline the scenario ended up being a SQL DB on an Azure VM and not pure SQL Azure.  This scenario is technically treated the same as "on-premise" support which will be supported sometime in Fall 2016.

**Comment by mikemagnusw** [comment]
> This scenario is technically treated the same as "on-premise" support which will be supported sometime in Fall 2016.

Sorry, what? Does this mean that having uploading to the PowerBI Embedded service a .pbix which has a DirectQuery source as a 'plain' SQL connection, we should have no expectation of it working? Regardless of Patch GatewayDatasource. Where is this documented?

**Comment by wbreza** [comment]
@mikemagnusw - I understand the frustration and have created a new issue that we'll keep open till the underlying service supports this scenario.

**Comment by julianmbs** [comment]
Hi, coming back to our conversation from August - does Power BI Embedded support on-premise SQL and Analysis Services yet?
