### ISSUE TITLE
error on install. What does this mean?

### ISSUE THREAD

**Issue by DanielOhYeah** [Microsoft/PowerBI-Cli#35]
PS C:\PowerShell\Portal> npm install powerbi-cli -g
npm : npm WARN deprecated node-uuid@1.4.7: use uuid module instead
At line:1 char:1
+ npm install powerbi-cli -g
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN deprec... module instead:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
C:\Users\RefreshPowerBI\AppData\Roaming\npm\powerbi -> C:\Users\RefreshPowerBI\AppData\Roaming\npm\node_modules\powerbi-cli\bin\cli
powerbi-cli@1.0.4 C:\Users\RefreshPowerBI\AppData\Roaming\npm\node_modules\powerbi-cli
â”œâ”€â”€ colors@1.1.2
â”œâ”€â”€ commander@2.9.0 (graceful-readlink@1.0.1)
â”œâ”€â”€ powerbi-api@1.0.1 (jwt-simple@0.5.1)
â”œâ”€â”€ ms-rest@1.15.2 (duplexer@0.1.1, underscore@1.8.3, through@2.3.8, tunnel@0.0.4, request@2.74.0, moment@2.17.0)
â””â”€â”€ lodash@4.17.2

**Comment by ali-hamud** [comment]
still happen for you?

**Comment by DanielOhYeah** [comment]
I still get this warning but otherwise ok.

<
  npm install powerbi-cli -g
  npm : npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
  At line:3 char:1
+ npm install powerbi-cli -g
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (npm WARN deprec... module instead:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
>
