### ISSUE TITLE
Get embed URL using CLI

### ISSUE THREAD

**Issue by rhuanbarreto** [Microsoft/PowerBI-Cli#36]
I'm using the new demo of the javascript API on

https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html

How can I get the Embed URL using the CLI? I got the token and report id with the command powerbi create-embed-token.

**Comment by err-unknown-username** [comment]
Did you work this out? I'm looking for the same.

**Comment by ali-hamud** [comment]
please update to version 1.0.6 (latest)
and call powerbi get-reports

have fun :)
