### ISSUE TITLE
problems updating connection 

### ISSUE THREAD

**Issue by sjoss** [Microsoft/PowerBI-Cli#48]
We have some problems when trying to update the connection on a direct query report.

we manually update the connection with cmd : 
```
powerbi update-connection -u user -p pwd -s "Data Source=server.database.windows.net,1433;Initial Catalog=initCat;Persist Security Info=False;User ID=user;Password=pwd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;" -d datasetID
```
result is : 
```
[ powerbi ] Found dataset!
[ powerbi ] Id: id
[ powerbi ] Name: CuttingTime
[ powerbi ] Updating connection string...
[ powerbi ] parameters[valueElement] must be of type object.
[ powerbi ] Connection string successfully updated
[ powerbi ] Dataset:  dataset
[ powerbi ] ConnectionString:  Data Source= datasource info
[ powerbi ] Getting gateway datasources...
[ powerbi ] Found 1 Datasources for Dataset 
[ powerbi ] --------------------------------------------------------------------
[ powerbi ] Datesource ID:  DID
[ powerbi ] Gateway ID:  GID
[ powerbi ] Credential Type:  undefined
[ powerbi ] Datasource Type:  Sql
[ powerbi ] Updating datasource credentials...
[ powerbi ] Successfully updated datasource credentials!
[ powerbi ] Datasource ID:  DATASOURCEID
[ powerbi ] Gateway ID:  GID
```

`[ powerbi ] parameters[valueElement] must be of type object`. is red and my Datasource is not updated

`powerbi version`=> 1.0.6
back to 1.0.4 => same result

My last  ok jenkins job :  10/02/2017 with 1.0.4 
first ko job : 13/02/2017 with 1.0.6

**Comment by ali-hamud** [comment]
Thanks for opening issue for that.
we will try to reproduce the bug, and will update.

**Comment by kirkone** [comment]
Hi,

maybe this has a relation to this #20 ?
it is closed for a while now but the error semms to be the same.

I have the same issue here. I can not update the connection string.

CU
KirK

**Comment by mepa1363** [comment]
@sjoss Just remove the quotes from the connection string and it'll work fine.

**Comment by sjoss** [comment]
@mepa1363  with this cmd : 
``` 
powerbi update-connection -u user -p pwd -s Data Source=server.database.windows.net,1433;Initial Catalog=initCat;Persist Security Info=False;User ID=user;Password=pwd;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; -d datasetID
```
I have same issue...
And in jenkins job with a powershell script, it don't work

**Comment by mepa1363** [comment]
@sjoss try this connection string:

`Data Source=jwndb.database.windows.net;Initial Catalog=dbname;User ID=user;Password=pwd;`

I'm using it everyday and it works!

**Comment by BretStateham** [comment]
Having the same issues on multiple machines.  Tried versions 1.0.8,1.0.6, 1.0.3, 1.0.2

**Comment by ali-hamud** [comment]
we were able to reproduce this bug.
we will fix it soon.

**Comment by ali-hamud** [comment]
issue fixed.
please re-install powerbi-cli and try again.

to install:
npm install powerbi-cli -g

bug fixed in dependency library:
[https://github.com/Microsoft/PowerBI-Node/pull/33](https://github.com/Microsoft/PowerBI-Node/pull/33)
