### ISSUE TITLE
cli-create-embed-token cannot set expiration

### ISSUE THREAD

**Issue by kmorihiro** [Microsoft/PowerBI-Cli#53]
Hello,

I want to set a token expiration date by cli-create-embed-token.
`createReportEmbedToken` function of powerbi-api can set expiration (see below), but cli-create-embed-token doesn't set any expiration parameter to it.

**https://github.com/Microsoft/PowerBI-Node/blob/master/lib/core/powerBIToken.ts#L17**

**Comment by ali-hamud** [comment]
Thank you. we will get to it.
I've no ETA yet.
You can also contribute to our repository :)

Thanks again.
