### ISSUE TITLE
400 error when importing pbix

### ISSUE THREAD

**Issue by anweiss** [Microsoft/PowerBI-Cli#6]
Every time I try to import a pbix using the `powerbi import` command, I get an HTTP 400 status code with no additional details about the error. A subsequent call to `powerbi get-reports` returns `No reports found within workspace: <workspace_id>`

**Comment by wbreza** [comment]
The failure should include a `RequestID`.  If you can let me know what that is I can dig into your specific issue further.

**Comment by anweiss** [comment]
Thanks @wbreza ...see below:

```
requestid :  e57f7901-f278-4042-998c-6a459f483f9e
```

**Comment by wbreza** [comment]
Thanks @anweiss.  Are you setting a dataset display name?  The CLI is currently not enforcing this but it is required on the backend.

Try again passing in the displayName param.

`powerbi import -f <file> -n YourDatasetName`

**Comment by anweiss** [comment]
ah ok...so that seems to have imported the file, however, it shows that the import state is _Failed_ ...how can one troubleshoot import failures?

**Comment by wbreza** [comment]
We're working on exposing better error messages.  In the meantime you can proxy your HTTP traffic through an HTTP tracing tool like fiddler and inspect the raw response output.

If you still aren't seeing anything useful provide me the Request Id and I can take a quick look.

**Comment by anweiss** [comment]
ok no worries at all. thanks!! closing...
