### ISSUE TITLE
How to embedded Power Bi Dashboard

### ISSUE THREAD

**Issue by Malith1994124** [Microsoft/PowerBI-Cli#62]
I see Microsoft provide solution to how to embedded power bi report. In my case i create power report in desktop and then publish in https://app.powerbi.com/ and create a dashboard. Now i need to know how to embedded that dashboard. Can you please provide me a solution?

**Comment by ali-hamud** [comment]
Hi,
You can use PowerBI-Javascript SDK:
https://github.com/Microsoft/PowerBI-javascript

Usage example is here:
https://github.com/Microsoft/PowerBI-Developer-Samples/tree/master/PowerBI.com%20Integrate

please re-open if this doesn't help.
