### ISSUE TITLE
Error Importing a Report: Microsoft.PowerBI.ServiceContracts.PowerBIEntityFrameworkOperationException

### ISSUE THREAD

**Issue by jordiruiz** [Microsoft/PowerBI-Cli#63]
Hello,

I receive the following error when I try to import reports:

![image](https://cloud.githubusercontent.com/assets/2950890/25895493/641dc6a0-3580-11e7-960f-b9abf91c18b1.png)

**Comment by ReubenPearse** [comment]
I'm also experiencing the same issue as shown in the screenshot below:
![powerbi_error](https://cloud.githubusercontent.com/assets/28599677/25901753/a06bec5e-358f-11e7-9094-f368cff6cebc.PNG)

**Comment by jordiruiz** [comment]
It's working now

**Comment by jonn220** [comment]
How did you solve this issue? Please help, I'm facing same issue with one of the repors

We couldn't import data from Power BI Desktop File
Make sure you're entering the information correctly.
Please try again later or contact support. If you contact support, please provide these details.
Activity ID: 674224a0-4432-4929-ac6f-e96f587c26a8
Request ID: a40e6cd6-3fd4-7555-dde1-b1c1e2e4457d
Correlation ID: 31c5412b-05bf-57d5-4904-d95024cbc59e
Status code: 400
Time: Sat Apr 25 2020 23:26:37 GMT+0530 (India Standard Time)
Service version: 13.0.13035.244
Client version: 2004.2.00695-train
Cluster URI: https://wabi-south-east-asia-b-primary-redirect.analysis.windows.net/

**Comment by jonn220** [comment]
> 
> 
> It's working now

How did you solve this issue? Please help, I'm facing same issue with one of the repors

We couldn't import data from Power BI Desktop File
Make sure you're entering the information correctly.
Please try again later or contact support. If you contact support, please provide these details.
Activity ID: 674224a0-4432-4929-ac6f-e96f587c26a8
Request ID: a40e6cd6-3fd4-7555-dde1-b1c1e2e4457d
Correlation ID: 31c5412b-05bf-57d5-4904-d95024cbc59e
Status code: 400
Time: Sat Apr 25 2020 23:26:37 GMT+0530 (India Standard Time)
Service version: 13.0.13035.244
Client version: 2004.2.00695-train
Cluster URI: https://wabi-south-east-asia-b-primary-redirect.analysis.windows.net/

**Comment by jordiruiz** [comment]
It worked again without do anything from my side
