### ISSUE TITLE
Is there a replacement for this package?

### ISSUE THREAD

**Issue by jhoerr** [Microsoft/PowerBI-Cli#71]
Now that this package is deprecated is there a supported replacement or something offering similar functionality?

**Comment by jaykilleen** [comment]
I have the same question. Seems like I am late to the party on requiring a cli functionality for PowerBI.

**Comment by IvanJosipovic** [comment]
Looks like this might be the replacement: https://powerbi.microsoft.com/en-us/blog/announcing-apis-and-powershell-cmdlets-for-power-bi-administrators/

**Comment by jordanmills** [comment]
Well it looks like that link is describing this project.
